import React from "react";
import { Container, Row } from "react-bootstrap";
import "./home.css";

export default function home() {
  return (
    <div className="">
      <section>
        <Container fluid className="bg-img img-fluid">
          <div className="container">
            <h5 className="text-center mt me-5 bd-highlight d-inline-block">
              Welcome to the Spoiled Young Ape Club (SYAC)
            </h5>
            <div className="row">
              <div className="col-lg-12">
                <img src="Group-2584.png" alt="" />
              </div>
            </div>
          </div>
        </Container>
      </section>
      <section>
        <div className="container-fluid bg-black">
          <div className="container">
            <div className="row">
              <div className="col-lg-5 logo-img">
                <img src="image-7.png" alt="" />
              </div>
              <div className="col-lg-6 title ">
                <h4>SYAC</h4>
                <p>
                  Inspired by the TV show “Growing Pains”, our apes are just
                  like the Seaver - experiencing growing pains and looking to
                  cause trouble. These 7,777 unique young apes are looking for
                  ways to entertain themselves by getting up to mischief.
                </p>
                <p>
                  SYAC is a NFT collection consisting of young apes with over
                  200 accessories, expressions and clothing generated by an
                  algorithm. Our NFT Collection offers high utilities to our
                  members in a sustainable way with IRL bitcoin mining and each
                  NFT holder will earn 10 tokens by holding our NFTs per day.
                  This means that you can enjoy earning passive income whilst
                  holding our NFTs.
                </p>
                <p>
                  OWN A SYAC HIGH UTILITY NFT AND BECOME AN APE MINING FARM
                  OWNER
                </p>
              </div>
            </div>
            <div className="row title mt-5 d-flex justify-content-right">
              <h3>APE MINING FARM</h3>
              <div className="col-lg-12">
                <img src="ape-bitcoin.png" alt="" />
                <div>
                  <h4>JOIN THE COMMUNITY</h4>
                  <p>
                    Follow us on Twitter, Instagram and join our Discord channel
                    to learn more about us.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
