import React from "react";
import "./team.css";
import { Accordion } from "react-bootstrap";
export default function team() {
  return (
    <div className="container-fluid bg-dark" id="team">
      <div className="container ">
        <div className="row d-flex justify-content-center">
          <h3 className="team-title mt-5">THE TEAM</h3>
          <div className="col-lg-8 ">
            <img className="img-fluid" src="Group-2595.png" alt="" />
          </div>
          <div className="col-lg-8 content mt-5">
            <p className="text-white text-left">
              It all started with three friends with inspiration from Apes.
              Tarzan is heavily involved with business as an entrepreneur, who
              loves to collect classic cars and NFTs. Achila is an artist who
              brings art to life with her amazing talents. Karry is a blockchain
              expert who writes gibberish codes on his computer. We don’t
              understand it, not even a tiny byte of it, but it somehow
              magically works. All are greatly interested in NFTs and their
              lore. They combined their powers to bring this collection to life.
            </p>
          </div>
          <h3 className="team-title mt-5" id="faq">
            FAQ
          </h3>
          <div className="col-lg-8 mb-5">
            <Accordion defaultActiveKey="0" variant="link">
              <Accordion.Item eventKey="0">
                <Accordion.Header>What is the SYAC Project?</Accordion.Header>
                <Accordion.Body>
                  SYAC is an NFT collection consisting of young apes with over
                  200 accessories, expressions and clothing generated by an
                  algorithm. We are the first NFT Collection in the world that
                  has Mining Utility to benefit our members in a sustainable
                  way. Ethereum blockchain. ERC-721
                </Accordion.Body>
              </Accordion.Item>
              <Accordion.Item eventKey="1">
                <Accordion.Header>
                  What will be the mint price?
                </Accordion.Header>
                <Accordion.Body>
                  Our young apes will be listed at 0.05ETH per mint
                </Accordion.Body>
              </Accordion.Item>
              <Accordion.Item eventKey="2">
                <Accordion.Header>
                  What will be the mint price?
                </Accordion.Header>
                <Accordion.Body>
                  Our young apes will be listed at 0.05ETH per mint
                </Accordion.Body>
              </Accordion.Item>
              <Accordion.Item eventKey="3">
                <Accordion.Header>
                  What will be the mint price?
                </Accordion.Header>
                <Accordion.Body>
                  Our young apes will be listed at 0.05ETH per mint
                </Accordion.Body>
              </Accordion.Item>
              <Accordion.Item eventKey="4">
                <Accordion.Header>
                  What will be the mint price?
                </Accordion.Header>
                <Accordion.Body>
                  Our young apes will be listed at 0.05ETH per mint
                </Accordion.Body>
              </Accordion.Item>
              <Accordion.Item eventKey="5">
                <Accordion.Header>
                  What will be the mint price?
                </Accordion.Header>
                <Accordion.Body>
                  Our young apes will be listed at 0.05ETH per mint
                </Accordion.Body>
              </Accordion.Item>
              <Accordion.Item eventKey="6">
                <Accordion.Header>
                  What will be the mint price?
                </Accordion.Header>
                <Accordion.Body>
                  Our young apes will be listed at 0.05ETH per mint
                </Accordion.Body>
              </Accordion.Item>
            </Accordion>
          </div>
        </div>
      </div>
    </div>
  );
}
